#!/usr/bin/env bash
# deploy-contracts.sh — Deploy all StellarVerse contracts to Stellar testnet (or mainnet)
# Usage:
#   ./scripts/deploy-contracts.sh                    # testnet (default)
#   STELLAR_NETWORK=mainnet ./scripts/deploy-contracts.sh

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
NETWORK="${STELLAR_NETWORK:-testnet}"
SOURCE_ACCOUNT="${STELLAR_SOURCE_ACCOUNT:-deployer}"
CONTRACTS_DIR="$(cd "$(dirname "$0")/../contracts" && pwd)"
OUTPUT_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env.contracts"

case "$NETWORK" in
  testnet)
    RPC_URL="https://soroban-testnet.stellar.org"
    NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
    ;;
  mainnet)
    RPC_URL="https://soroban.stellar.org"
    NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
    ;;
  *)
    echo "ERROR: Unknown network '$NETWORK'. Use 'testnet' or 'mainnet'." >&2
    exit 1
    ;;
esac

# ── Helpers ───────────────────────────────────────────────────────────────────
log()  { echo "▶ $*"; }
ok()   { echo "✔ $*"; }
fail() { echo "✘ $*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "'$1' is not installed. See docs/DEVELOPMENT.md."
}

# ── Pre-flight checks ─────────────────────────────────────────────────────────
require_cmd soroban
require_cmd cargo

log "Network:  $NETWORK"
log "RPC URL:  $RPC_URL"
log "Source:   $SOURCE_ACCOUNT"
echo ""

# Ensure deployer key exists; generate + fund on testnet if missing
if ! soroban keys show "$SOURCE_ACCOUNT" >/dev/null 2>&1; then
  if [ "$NETWORK" = "testnet" ]; then
    log "Generating '$SOURCE_ACCOUNT' key and funding from friendbot..."
    soroban keys generate "$SOURCE_ACCOUNT" --network "$NETWORK"
    soroban keys fund "$SOURCE_ACCOUNT" --network "$NETWORK"
    ok "Account funded: $(soroban keys address "$SOURCE_ACCOUNT")"
  else
    fail "Key '$SOURCE_ACCOUNT' not found. Add it with: soroban keys add $SOURCE_ACCOUNT"
  fi
fi

DEPLOYER_ADDRESS=$(soroban keys address "$SOURCE_ACCOUNT")
log "Deployer address: $DEPLOYER_ADDRESS"
echo ""

# ── Build ─────────────────────────────────────────────────────────────────────
log "Building contracts (wasm32-unknown-unknown)..."
(
  cd "$CONTRACTS_DIR"
  cargo build --target wasm32-unknown-unknown --release --quiet
)
ok "Build complete."
echo ""

WASM_DIR="$CONTRACTS_DIR/target/wasm32-unknown-unknown/release"

# ── Deploy helper ─────────────────────────────────────────────────────────────
deploy_contract() {
  local name="$1"
  local wasm="$2"
  log "Deploying $name..."
  local contract_id
  contract_id=$(soroban contract deploy \
    --wasm "$wasm" \
    --source "$SOURCE_ACCOUNT" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE")
  ok "$name deployed: $contract_id"
  echo "$contract_id"
}

invoke() {
  local contract_id="$1"; shift
  soroban contract invoke \
    --id "$contract_id" \
    --source "$SOURCE_ACCOUNT" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" \
    -- "$@"
}

# ── Deploy contracts ──────────────────────────────────────────────────────────

# 1. SVRSToken
SVRS_ID=$(deploy_contract "SVRSToken" "$WASM_DIR/svrs_token.wasm")
log "Initializing SVRSToken..."
invoke "$SVRS_ID" initialize \
  --admin "$DEPLOYER_ADDRESS" \
  --name "StellarVerse Token" \
  --symbol "SVRS" \
  --decimals 7
ok "SVRSToken initialized."
echo ""

# 2. LandNFT
LAND_ID=$(deploy_contract "LandNFT" "$WASM_DIR/land_nft.wasm")
log "Initializing LandNFT..."
invoke "$LAND_ID" initialize --admin "$DEPLOYER_ADDRESS"
ok "LandNFT initialized."
echo ""

# 3. AssetNFT
ASSET_ID=$(deploy_contract "AssetNFT" "$WASM_DIR/asset_nft.wasm")
log "Initializing AssetNFT..."
invoke "$ASSET_ID" initialize --admin "$DEPLOYER_ADDRESS"
ok "AssetNFT initialized."
echo ""

# 4. Marketplace
MARKET_ID=$(deploy_contract "Marketplace" "$WASM_DIR/marketplace.wasm")
log "Initializing Marketplace (fee: 2.5%)..."
invoke "$MARKET_ID" initialize \
  --admin "$DEPLOYER_ADDRESS" \
  --land-nft "$LAND_ID" \
  --asset-nft "$ASSET_ID" \
  --svrs-token "$SVRS_ID" \
  --fee-bps 250
ok "Marketplace initialized."
echo ""

# ── Write .env.contracts ──────────────────────────────────────────────────────
cat > "$OUTPUT_FILE" <<EOF
# Auto-generated by deploy-contracts.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Network: $NETWORK
# Source this file or copy values into .env

NEXT_PUBLIC_STELLAR_NETWORK=$NETWORK
NEXT_PUBLIC_SOROBAN_RPC_URL=$RPC_URL
NEXT_PUBLIC_NETWORK_PASSPHRASE="$NETWORK_PASSPHRASE"

NEXT_PUBLIC_SVRS_TOKEN_CONTRACT_ID=$SVRS_ID
NEXT_PUBLIC_LAND_NFT_CONTRACT_ID=$LAND_ID
NEXT_PUBLIC_ASSET_NFT_CONTRACT_ID=$ASSET_ID
NEXT_PUBLIC_MARKETPLACE_CONTRACT_ID=$MARKET_ID
EOF

ok "Contract IDs saved to $OUTPUT_FILE"
echo ""
echo "════════════════════════════════════════════════════════"
echo "  Deployment complete!"
echo ""
echo "  SVRSToken:   $SVRS_ID"
echo "  LandNFT:     $LAND_ID"
echo "  AssetNFT:    $ASSET_ID"
echo "  Marketplace: $MARKET_ID"
echo ""
echo "  To use these IDs, run:"
echo "    source $OUTPUT_FILE"
echo "  or copy the values into your .env file."
echo "════════════════════════════════════════════════════════"
